name: Build and deploy Python app to Azure Web App - bruno-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package app files
        run: zip -r release.zip . -x "venv/*" ".git/*" ".github/*"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Confirm release.zip exists
        run: ls -lh release.zip
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bruno-bot'
          slot-name: 'live'
          package: '${{ github.workspace }}/release.zip'

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bruno-bot'
          slot-name: 'production'
          package: '${{ github.workspace }}/release.zip'

      - name: Deploy to Azure Web App (test)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bruno-bot'
          slot-name: 'live-g5brg7dsekb7fed8'
          package: '${{ github.workspace }}/release.zip'
